package model.DAO.AccessData

class DestinationData {
    companion object {
        val destinations: Map<String, List<String>> = mapOf(
            //4
            "4 Chemins" to listOf("MERIGNAC", "4 Chemins"),
            //5
            "5 Chemins" to listOf("LE HAILLAN", "5 Chemins"),
            //A
            "Achard" to listOf("BORDEAUX", "Rue Achard"),
            "Aéroport" to listOf("MERIGNAC", "Aéroport"),
            "Aeroport" to listOf("MERIGNAC", "Aéroport"),
            "Alfred De Vigny" to listOf("MERIGNAC", "Alfred de Vigny"),
            "Alouette" to listOf("PESSAC", "France Alouette"),
            "Ambarès Centre" to listOf("AMBARÈS", "Centre"),
            "André Ricard" to listOf("BORDEAUX", "André Ricard"),
            "Arena" to listOf("FLOIRAC", "Arkéa Arena"),
            //B
            "BA 106 (terminus)" to listOf("MERIGNAC", "BA 106"),
            "Barrière d'Ornano" to listOf("BORDEAUX", "Barrière d'Ornano"),
            "Barrière du Médoc" to listOf("BORDEAUX", "Barrière du Médoc"),
            "Barriere Medoc" to listOf("BORDEAUX", "Barrière du Médoc"),
            "Base sous-marine" to listOf("BORDEAUX", "Base sous-marine"),
            "Bassins à Flot" to listOf("BORDEAUX", "Bassins à Flot"),
            "Beaudésert" to listOf("MERIGNAC", "Beaudésert"),
            "Beausite" to listOf("CENON", "Beausite"),
            "Beausoleil" to listOf("GRADIGNAN", "Beausoleil"),
            "Belle Rive" to listOf("SAINT LOUIS DE MONTFERRAND", "Belle Rive"),
            "Berge De Garonne" to listOf("BORDEAUX", "Berges de la Garonne"),
            "Berges de Garonne" to listOf("BORDEAUX", "Berges de la Garonne"),
            "Bernatet" to listOf("AMBARÈS", "Bernatet"),
            "Blanquefort" to listOf("BLANQUEFORT", "Gare"),
            "Bougnard" to listOf("PESSAC", "Bougnard"),
            "Bouliac Ccial" to listOf("BOULIAC", "Centre Commercial"),
            "Bourgogne" to listOf("BORDEAUX", "Porte de Bourgogne"),
            "Brandenburg" to listOf("BORDEAUX", "Brandenburg"),
            "Bre Pessac (bvd)" to listOf("BORDEAUX", "Barrière de Pessac"),
            "Brulatour" to listOf("BORDEAUX", "Brulatour"),
            "Buttinière" to listOf("LORMONT", "Buttinière"),
            //C
            "Camille Jullian" to listOf("BORDEAUX", "Lycée Camille Jullian"),
            "Camping" to listOf("BORDEAUX", "Camping International"),
            "Camping Internat" to listOf("BORDEAUX", "Camping International"),
            "Candau" to listOf("PESSAC", "Candau"),
            "Cantinolle" to listOf("EYSINES", "Cantinolle"),
            "Capc Musee D'Art" to listOf("BORDEAUX", "CAPC Musée d'Art Contemporain"),
            "Cap de Bos" to listOf("PESSAC", "Cap de Bos"),
            "Capelle" to listOf("BORDEAUX", "Capelle"),
            "Carle Vernet" to listOf("BORDEAUX", "Carle Vernet"),
            "Caychac" to listOf("BLANQUEFORT", "Caychac"),
            "Cenon Gare" to listOf("CENON", "Gare"),
            "Centre Commercial" to listOf("BORDEAUX", "Centre Commercial du Lac"),
            "Centre-Forum" to listOf("TALENCE", "Forum"),
            "Château Rouquey" to listOf("MERIGNAC", "Château Rouquey"),
            "Chemin du Sourd" to listOf("CARBON BLANC", "Chemin du Sourd"),
            "Cimetière Interco" to listOf("MERIGNAC", "Cimetière Intercommunal"),
            "Claveau" to listOf("BORDEAUX", "Claveau"),
            "Collège Chambéry" to listOf("VILLENAVE D'ORNON", "Collège Chambéry"),
            "Collège C Massé" to listOf("AMBARÈS", "Collège Claude Massé"),
            "Coll Aliénor Aq" to listOf("MARTIGNAS SUR JALLE", "Collège Aliénor d'Aquitaine"),
            "Coll Emile Zola" to listOf("LE HAILLAN", "Collège Émile Zola"),
            "Coll Simone Veil" to listOf("CARBON BLANC", "Collège Simone Veil"),
            "Courréjean" to listOf("VILLENAVE D'ORNON", "Courréjean"),
            "Cracovie" to listOf("BORDEAUX", "Cracovie"),
            //D
            "Délestage TyF" to listOf("ARTIGUES PRÈS BORDEAUX", "Tout y Faut"),
            "Doyen Brus" to listOf("PESSAC", "Doyen Brus"),
            "Dravemont" to listOf("FLOIRAC", "Dravemont"),
            "Du Roy" to listOf("AMBARÈS", "Du Roy"),
            //E
            "Ecoparc" to listOf("BLANQUEFORT", "Ecoparc"),
            "Ernest Renan" to listOf("BORDEAUX", "Ernest Renan"),
            "Escarraguel" to listOf("AMBÈS", "Escarraguel"),
            "Eysines Centre" to listOf("EYSINES", "Centre"),
            //F
            "Floirac Dravemont" to listOf("FLOIRAC", "Dravemont"),
            "Fondaudege" to listOf("BORDEAUX", "Fondaudège Muséum"),
            "Fontaine D'Arlac" to listOf("MERIGNAC", "Fontaine d'Arlac"),
            "Fontaine d'Arlac" to listOf("MERIGNAC", "Fontaine d'Arlac"),
            "Fontanieu" to listOf("PAREMPUYRE", "Fontanieu"),
            "Fontderode" to listOf("ARTIGUES PRÈS BORDEAUX", "Fontderode"),
            "Fort Lajard" to listOf("AMBÈS", "Fort Lajard"),
            "France.Alouette" to listOf("PESSAC", "France Alouette"),
            "Frankton Terminus" to listOf("BLANQUEFORT", "Frankton"),
            "Frères Portmann" to listOf("BORDEAUX", "Frères Portmann"),
            //G
            "Galaxie" to listOf("SAINT MÉDARD EN JALLES", "Galaxie"),
            "Galerie Tatry" to listOf("BORDEAUX", "Galerie Tatry"),
            "Galin" to listOf("BORDEAUX", "Galin"),
            "Galin Terminus" to listOf("BORDEAUX", "Galin"),
            "Gambetta" to listOf("BORDEAUX", "Gambetta"),
            "Gare Blanquefort" to listOf("BLANQUEFORT", "Gare"),
            "Gare De Begles" to listOf("BÈGLES", "Gare"),
            "Gare de Bruges" to listOf("BRUGES", "Gare"),
            "Gare Routière" to listOf("SAINT MÉDARD EN JALLES", "Gare Routière"),
            "Gare Saint-Jean" to listOf("BORDEAUX", "Gare Saint Jean"),
            "Gare St Jean" to listOf("BORDEAUX", "Gare Saint Jean"),
            "Gavinies" to listOf("BORDEAUX", "Gaviniès"),
            "Gaviniès" to listOf("BORDEAUX", "Gaviniès"),
            "G. Fauré Terminus" to listOf("BORDEAUX", "Gabriel Fauré"),
            "Gradignan Centre" to listOf("GRADIGNAN", "Centre"),
            "Grand Parc" to listOf("BORDEAUX", "Grand Parc"),
            //H
            "Haillan Rostand" to listOf("LE HAILLAN", "Rostand"),
            "Haillan-Rostand" to listOf("LE HAILLAN", "Rostand"),
            "Henri Barbusse" to listOf("MERIGNAC", "Henri Barbusse"),
            "Hippodrome" to listOf("LE BOUSCAT", "Hippodrome"),
            "Hôpital Pellegrin" to listOf("BORDEAUX", "Hôpital Pellegrin"),
            "Hôpital Suburbain" to listOf("LE BOUSCAT", "Hôpital Suburbain"),
            "Hop. Pellegrin" to listOf("BORDEAUX", "Hôpital Pellegrin"),
            //I
            "IMA" to listOf("MERIGNAC", "IMA"),
            "Iris" to listOf("LORMONT", "Iris"),
            "Issac" to listOf("SAINT MÉDARD EN JALLES", "Issac"),
            //J
            "Jardin Botanique" to listOf("BORDEAUX", "Jardin Botanique"),
            "Julien" to listOf("SAINT MÉDARD EN JALLES", "Julien"),
            //L
            "La Belle Etoile" to listOf("BOULIAC", "La Belle Étoile"),
            "La Boétie" to listOf("LE TAILLAN", "La Boétie"),
            "La Chênaie" to listOf("BASSENS", "La Chênaie"),
            "La Cite Du Vin" to listOf("BORDEAUX", "La Cité du Vin"),
            "La Cité du Vin" to listOf("BORDEAUX", "La Cité du Vin"),
            "La Gardette" to listOf("BASSENS/CARBON BLANC", "La Gardette"),
            "Landegrand" to listOf("PAREMPUYRE", "Landegrand"),
            "La Renney" to listOf("BLANQUEFORT", "La Renney"),
            "Lartigue" to listOf("BORDEAUX", "Lartigue"),
            "Lauriers" to listOf("LORMONT", "Lauriers"),
            "Le Grand Caillou" to listOf("EYSINES", "Le Grand Caillou"),
            "Le Plateau" to listOf("EYSINES", "Le Plateau"),
            "Le Trinquet" to listOf("PESSAC", "Le Trinquet"),
            "Les Aubiers" to listOf("BORDEAUX", "Les Aubiers"),
            "Les Ecoles" to listOf("MARTIGNAS SUR JALLE", "Les Écoles"),
            "Les Pins" to listOf("MERIGNAC", "Les Pins"),
            "Les Renardeaux" to listOf("MERIGNAC", "Les Renardeaux"),
            "Libération" to listOf("PAREMPUYRE", "Libération"),
            "Lormont Bas" to listOf("LORMONT", "Bas"),
            "Lycée Ch Peguy" to listOf("EYSINES", "Lycée Charles Peguy"),
            "Lycée Daguin" to listOf("MERIGNAC", "Lycée Daguin"),
            "Lycée des Graves" to listOf("GRADIGNAN", "Lycée des Graves"),
            "Lycée du Bâtiment" to listOf("BLANQUEFORT", "Lycée du Bâtiment"),
            "Lycée P Clément" to listOf("PESSAC", "Lycée Pape Clément"),
            "Lycée Sud Médoc" to listOf("SAINT AUBIN", "Lycée Sud Médoc"),
            "Lycée V Havel" to listOf("BÈGLES", "Lycée Vàclav Havel"),
            "Lycee V. Havel" to listOf("BÈGLES", "Lycée Vàclav Havel"),
            //M
            "Magonty" to listOf("PESSAC", "Magonty"),
            "Mairie du Bouscat" to listOf("LE BOUSCAT", "Mairie"),
            "Malartic" to listOf("GRADIGNAN", "Malartic"),
            "Martignas Centre" to listOf("MARTIGNAS SUR JALLE", "Centre"),
            "Max Linder" to listOf("AMBARÈS", "Max Linder"),
            "MECA" to listOf("BORDEAUX", "MÉCA"),
            "Meriadeck" to listOf("BORDEAUX", "Mériadeck"),
            "Mériadeck" to listOf("BORDEAUX", "Mériadeck"),
            "Mérignac Arlac" to listOf("MERIGNAC", "Fontaine d'Arlac"),
            "Merignac Centre" to listOf("MERIGNAC", "Centre"),
            "Mérignac Centre" to listOf("MERIGNAC", "Centre"),
            "Mérignac Phare" to listOf("MERIGNAC", "Phare"),
            "Mérignac Soleil" to listOf("MERIGNAC", "Soleil"),
            "Mérignac Soleil 1" to listOf("MERIGNAC", "Soleil (Porte 1)"),
            "Monbalon 2" to listOf("PESSAC", "Monbalon 2"),
            "Montaigne" to listOf("PESSAC", "Montaigne Montesquieu"),
            "Morlette" to listOf("CENON", "La Morlette"),
            "Mouline" to listOf("CARBON BLANC", "Mouline"),
            "Musee Aquitaine" to listOf("BORDEAUX", "Musée d'Aquitaine"),
            "Musée d'Aquitaine" to listOf("BORDEAUX", "Musée d'Aquitaine"),
            //N
            "New York" to listOf("BORDEAUX", "New York"),
            //P
            "Palais de Justice" to listOf("BORDEAUX", "Palais de Justice"),
            "Parabelle" to listOf("AMBARÈS", "Parabelle"),
            "Parc des Expos" to listOf("BORDEAUX", "Parc des Expositions"),
            "Parc Des Expos" to listOf("BORDEAUX", "Parc des Expositions"),
            "Patinoire" to listOf("BORDEAUX", "Patinoire"),
            "Peixotto" to listOf("TALENCE", "Peixotto"),
            "Pelouse de Douet" to listOf("BORDEAUX", "Pelouse de Douet"),
            "Pessac Bougnard" to listOf("PESSAC", "Bougnard"),
            "Pessac Centre" to listOf("PESSAC", "Centre"),
            "Peychotte" to listOf("MERIGNAC", "Peychotte"),
            "Phare" to listOf("MERIGNAC", "Phare"),
            "Photonique" to listOf("PESSAC", "Cité Photonique"),
            "Pin Galant" to listOf("MERIGNAC", "Pin Galant"),
            "Pinsoles" to listOf("SAINT AUBIN", "Pinsoles"),
            "Piscine Chambéry" to listOf("VILLENAVE D'ORNON", "Piscine Chambéry"),
            "Place Mondésir" to listOf("MERIGNAC", "Place Mondésir"),
            "Place Ravezies" to listOf("LE BOUSCAT", "Place Ravezies"),
            "Pont de la Maye" to listOf("VILLENAVE D'ORNON", "Pont de la Maye"),
            "Préfecture" to listOf("BORDEAUX", "Préfecture"),
            "Pte de Bourgogne" to listOf("BORDEAUX", "Porte de Bourgogne"),
            "Pyrenees" to listOf("VILLENAVE D'ORNON", "Pyrénées"),
            "Pyrénées" to listOf("VILLENAVE D'ORNON", "Pyrénées"),
            //Q
            "Quai Français" to listOf("BASSENS", "Quai Français"),
            "Quarante Journaux" to listOf("BORDEAUX", "Quarante Journaux"),
            "Quatre Chemins" to listOf("MERIGNAC", "4 Chemins"),
            "Quinc. Fleuve" to listOf("BORDEAUX", "Quinconces Fleuve"),
            "Quinc Jean Jaurès" to listOf("BORDEAUX", "Quinconces (Jean Jaurès)"),
            "Quinconces" to listOf("BORDEAUX", "Quinconces"),
            "Quinconces Munich" to listOf("BORDEAUX", "Quinconces Munich"),
            "Quinsus" to listOf("AMBARÈS", "Quinsus"),
            //R
            "Ravezies" to listOf("LE BOUSCAT", "Place Ravezies"),
            "René Coty" to listOf("AMBARÈS", "René Coty"),
            "République" to listOf("BORDEAUX", "République"),
            "Rives d'Arcins" to listOf("BÈGLES", "Rives d'Arcins"),
            "Romainville" to listOf("PESSAC", "Romainville"),
            "Rostand" to listOf("LE HAILLAN", "Rostand"),
            //S
            "Saint Augustin" to listOf("BORDEAUX", "Saint Augustin"),
            "Saint-Exupéry" to listOf("BLANQUEFORT", "Saint Exupéry"),
            "Salengro" to listOf("BÈGLES", "Salengro"),
            "Souge" to listOf("MARTIGNAS SUR JALLE", "Souge"),
            "Stade Matmut" to listOf("BORDEAUX", "Stade Matmut Atlantique"),
            "Stade Municipal" to listOf("LE TAILLAN", "Stade Municipal"),
            "Stade Ornon" to listOf("GRADIGNAN", "Stade Ornon"),
            "Stalingrad" to listOf("BORDEAUX", "Stalingrad"),
            "Ste Catherine" to listOf("BORDEAUX", "Sainte Catherine"),
            "St Exupéry" to listOf("AMBÈS", "Saint Exupéry"),
            "St Nicolas" to listOf("BORDEAUX", "Saint Nicolas"),
            //T
            "Terres Neuves" to listOf("BÈGLES", "Terres Neuves"),
            "Thiers Benauge" to listOf("BORDEAUX", "Thiers Benauge"),
            "Thouars" to listOf("TALENCE", "Thouars"),
            "Toctoucau" to listOf("PESSAC", "Toctoucau"),
            //U
            "Unitec" to listOf("PESSAC", "Unitec"),
            //V
            "Vettiner" to listOf("BOULIAC", "Vettiner"),
            "Victoire Pasteur" to listOf("BORDEAUX", "Victoire"),
            "Village 5" to listOf("GRADIGNAN", "Village 5"),
            "Villenave Bourg" to listOf("VILLENAVE D'ORNON", "Bourg"),
            "Villenave Gare" to listOf("VILLENAVE D'ORNON", "Gare"),
            "Villepreux" to listOf("SAINT AUBIN", "Villepreux"),
            "Virecourt" to listOf("ARTIGUES PRÈS BORDEAUX", "Virecourt"),
            //Z
            "ZA Magellan" to listOf("PESSAC", "ZA Magellan"),
            "ZA Picot" to listOf("SAINT MÉDARD EN JALLES", "ZA Picot"),
            "Zone de Fret" to listOf("BRUGES", "Zone de Fret")
        )
    }
}