package model.DAO.AccessData

import com.diplay.ouestmonbus.R
import model.DTO.Line
import model.DTO.ListGroup

class LineData {
    companion object {
        val lines: ArrayList<Line> = arrayListOf(
            Line(59, "Tram A", R.drawable.tram_a, R.color.tram_a, ListGroup.TRAM),
            Line(60, "Tram B", R.drawable.tram_b, R.color.tram_b, ListGroup.TRAM),
            Line(61, "Tram C", R.drawable.tram_c, R.color.tram_c, ListGroup.TRAM),
            Line(62, "Tram D", R.drawable.tram_d, R.color.tram_d, ListGroup.TRAM),
            Line(1, "Lianes 1", R.drawable.lianes_1, R.color.lianes, ListGroup.LIANES),
            Line(2, "Lianes 2", R.drawable.lianes_2, R.color.lianes, ListGroup.LIANES),
            Line(3, "Lianes 3", R.drawable.lianes_3, R.color.lianes, ListGroup.LIANES),
            Line(4, "Lianes 4", R.drawable.lianes_4, R.color.lianes, ListGroup.LIANES),
            Line(5, "Lianes 5", R.drawable.lianes_5, R.color.lianes, ListGroup.LIANES),
            Line(67, "Lianes 7", R.drawable.lianes_7, R.color.lianes, ListGroup.LIANES),
            Line(6, "Lianes 8", R.drawable.lianes_8, R.color.lianes, ListGroup.LIANES),
            Line(7, "Lianes 9", R.drawable.lianes_9, R.color.lianes, ListGroup.LIANES),
            Line(12, "Lianes 15", R.drawable.lianes_15, R.color.lianes, ListGroup.LIANES),
            Line(13, "Lianes 16", R.drawable.lianes_16, R.color.lianes, ListGroup.LIANES),
            Line(17, "Ligne 20", R.drawable.ligne_20, R.color.ligne_p, ListGroup.LIGNEPRINCIPALE),
            Line(71, "Ligne 21", R.drawable.ligne_21, R.color.ligne_p, ListGroup.LIGNEPRINCIPALE),
            Line(72, "Ligne 22", R.drawable.ligne_22, R.color.ligne_p, ListGroup.LIGNEPRINCIPALE),
            Line(19, "Ligne 23", R.drawable.ligne_23, R.color.ligne_p, ListGroup.LIGNEPRINCIPALE),
            Line(20, "Ligne 24", R.drawable.ligne_24, R.color.ligne_p, ListGroup.LIGNEPRINCIPALE),
            Line(73, "Ligne 25", R.drawable.ligne_25, R.color.ligne_p, ListGroup.LIGNEPRINCIPALE),
            Line(22, "Ligne 26", R.drawable.ligne_26, R.color.ligne_p, ListGroup.LIGNEPRINCIPALE),
            Line(23, "Ligne 27", R.drawable.ligne_27, R.color.ligne_p, ListGroup.LIGNEPRINCIPALE),
            Line(24, "Ligne 28", R.drawable.ligne_28, R.color.ligne_p, ListGroup.LIGNEPRINCIPALE),
            Line(25, "Ligne 29", R.drawable.ligne_29, R.color.ligne_p, ListGroup.LIGNEPRINCIPALE),
            Line(74, "Ligne 30", R.drawable.ligne_30, R.color.ligne_l, ListGroup.LIGNELOCALE1),
            Line(26, "Lianes 31", R.drawable.lianes_31, R.color.lianes, ListGroup.LIGNELOCALE1),
            Line(75, "Ligne 32", R.drawable.ligne_32, R.color.ligne_l, ListGroup.LIGNELOCALE1),
            Line(27, "Ligne 33", R.drawable.ligne_33, R.color.ligne_l, ListGroup.LIGNELOCALE1),
            Line(28, "Ligne 34", R.drawable.ligne_34, R.color.ligne_l, ListGroup.LIGNELOCALE1),
            Line(29, "Lianes 35", R.drawable.lianes_35, R.color.lianes, ListGroup.LIGNELOCALE1),
            Line(30, "Ligne 37", R.drawable.ligne_37, R.color.ligne_l, ListGroup.LIGNELOCALE1),
            Line(31, "Ligne 38", R.drawable.ligne_38, R.color.ligne_l, ListGroup.LIGNELOCALE1),
            Line(32, "Lianes 39", R.drawable.lianes_39, R.color.lianes, ListGroup.LIGNELOCALE1),
            Line(84, "Ligne 51", R.drawable.ligne_51, R.color.ligne_d, ListGroup.LIGNEDIRECTE),
            Line(85, "Ligne 52", R.drawable.ligne_52, R.color.ligne_d, ListGroup.LIGNEDIRECTE),
            Line(134, "Ligne 53", R.drawable.ligne_53, R.color.ligne_d, ListGroup.LIGNEDIRECTE),
            Line(87, "Ligne 55", R.drawable.ligne_55, R.color.ligne_d, ListGroup.LIGNEDIRECTE),
            Line(89, "Ligne 57", R.drawable.ligne_57, R.color.ligne_d, ListGroup.LIGNEDIRECTE),
            Line(41, "TBNight", R.drawable.tbnight, R.color.tbnight, ListGroup.TBNIGHT),
            Line(135, "Ligne 60", R.drawable.ligne_60, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(136, "Ligne 61", R.drawable.ligne_61, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(47, "Ligne 64", R.drawable.ligne_64, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(137, "Ligne 65", R.drawable.ligne_65, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(138, "Ligne 66", R.drawable.ligne_66, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(50, "Ligne 67", R.drawable.ligne_67, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(139, "Ligne 69", R.drawable.ligne_69, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(140, "Ligne 70", R.drawable.ligne_70, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(97, "Ligne 71", R.drawable.ligne_71, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(98, "Ligne 72", R.drawable.ligne_72, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(99, "Ligne 73", R.drawable.ligne_73, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(100, "Ligne 74", R.drawable.ligne_74, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(101, "Ligne 75", R.drawable.ligne_75, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(102, "Ligne 76", R.drawable.ligne_76, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(103, "Ligne 77", R.drawable.ligne_77, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(104, "Ligne 78", R.drawable.ligne_78, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(105, "Ligne 79", R.drawable.ligne_79, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(106, "Ligne 80", R.drawable.ligne_80, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(107, "Ligne 81", R.drawable.ligne_81, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(108, "Ligne 82", R.drawable.ligne_82, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(109, "Ligne 83", R.drawable.ligne_83, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(110, "Ligne 84", R.drawable.ligne_84, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(111, "Ligne 85", R.drawable.ligne_85, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(112, "Ligne 86", R.drawable.ligne_86, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(58, "Ligne 87", R.drawable.ligne_87, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(114, "Ligne 89", R.drawable.ligne_89, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(115, "Ligne 90", R.drawable.ligne_90, R.color.ligne_l, ListGroup.LIGNELOCALE2),
            Line(128, "Navette Arena", R.drawable.navette_arena, R.color.navette_arena, ListGroup.LIGNESPECIALES),
            Line(127, "Navette Stade", R.drawable.navette_stade, R.color.navette_stade, ListGroup.LIGNESPECIALES),
            Line(132, "Navette Tram", R.drawable.navette_tram, R.color.navette_tram, ListGroup.LIGNESPECIALES),
            Line(130, "BatCUB", R.drawable.batcub, R.color.batcub, ListGroup.LIGNESPECIALES),
            )
    }
}