package model.DAO.AccessData

import com.diplay.ouestmonbus.R
import model.DTO.Line
import model.DTO.ListGroup

class LineData {
    companion object {
        val lines: ArrayList<Line> = arrayListOf(
            Line(59, "Tram A", R.drawable.tram_a, R.color.tram_a, ListGroup.TRAM),
            Line(60, "Tram B", R.drawable.tram_b, R.color.tram_b, ListGroup.TRAM),
            Line(61, "Tram C", R.drawable.tram_c, R.color.tram_c, ListGroup.TRAM),
            Line(62, "Tram D", R.drawable.tram_d, R.color.tram_d, ListGroup.TRAM),
            Line(1, "Lianes 1", R.drawable.lianes_1, R.color.lianes, ListGroup.LIANES),
            Line(2, "Lianes 2", R.drawable.lianes_2, R.color.lianes, ListGroup.LIANES),
            Line(3, "Lianes 3", R.drawable.lianes_3, R.color.lianes, ListGroup.LIANES),
            Line(4, "Lianes 4", R.drawable.lianes_4, R.color.lianes, ListGroup.LIANES),
            Line(5, "Lianes 5", R.drawable.lianes_5, R.color.lianes, ListGroup.LIANES),
            Line(7, "Lianes 7", R.drawable.lianes_7, R.color.lianes, ListGroup.LIANES),
            Line(8, "Lianes 8", R.drawable.lianes_8, R.color.lianes, ListGroup.LIANES),
            Line(9, "Lianes 9", R.drawable.lianes_9, R.color.lianes, ListGroup.LIANES),
            Line(15, "Lianes 15", R.drawable.lianes_15, R.color.lianes, ListGroup.LIANES),
            Line(16, "Lianes 16", R.drawable.lianes_16, R.color.lianes, ListGroup.LIANES),
            Line(20, "Ligne 20", R.drawable.ligne_20, R.color.principale, ListGroup.LIGNEPRINCIPALE),
            Line(64, "Ligne 21", R.drawable.ligne_21, R.color.principale, ListGroup.LIGNEPRINCIPALE),
            Line(65, "Ligne 22", R.drawable.ligne_22, R.color.principale, ListGroup.LIGNEPRINCIPALE),
            Line(21, "Ligne 23", R.drawable.ligne_23, R.color.principale, ListGroup.LIGNEPRINCIPALE),
            Line(22, "Ligne 24", R.drawable.ligne_24, R.color.principale, ListGroup.LIGNEPRINCIPALE),
            Line(23, "Ligne 25", R.drawable.ligne_25, R.color.principale, ListGroup.LIGNEPRINCIPALE),
            Line(66, "Ligne 26", R.drawable.ligne_26, R.color.principale, ListGroup.LIGNEPRINCIPALE),
            Line(24, "Ligne 27", R.drawable.ligne_27, R.color.principale, ListGroup.LIGNEPRINCIPALE),
            Line(25, "Ligne 28", R.drawable.ligne_28, R.color.principale, ListGroup.LIGNEPRINCIPALE),
            Line(67, "Ligne 29", R.drawable.ligne_29, R.color.principale, ListGroup.LIGNEPRINCIPALE),
            Line(68, "Locale 30", R.drawable.ligne_30, R.color.locale, ListGroup.LIGNELOCALE1),
            Line(26, "Lianes 31", R.drawable.lianes_31, R.color.lianes, ListGroup.LIGNELOCALE1),
            Line(27, "Locale 32", R.drawable.ligne_32, R.color.locale, ListGroup.LIGNELOCALE1),
            Line(69, "Locale 33", R.drawable.ligne_33, R.color.locale, ListGroup.LIGNELOCALE1),
            Line(28, "Locale 34", R.drawable.ligne_34, R.color.locale, ListGroup.LIGNELOCALE1),
            Line(29, "Lianes 35", R.drawable.lianes_35, R.color.lianes, ListGroup.LIGNELOCALE1),
            Line(31, "Locale 37", R.drawable.ligne_37, R.color.locale, ListGroup.LIGNELOCALE1),
            Line(70, "Locale 38", R.drawable.ligne_38, R.color.locale, ListGroup.LIGNELOCALE1),
            Line(71, "Lianes 39", R.drawable.lianes_39, R.color.lianes, ListGroup.LIGNELOCALE1),
            Line(81, "Directe 51", R.drawable.ligne_51, R.color.directe, ListGroup.LIGNEDIRECTE),
            Line(82, "Directe 52", R.drawable.ligne_52, R.color.directe, ListGroup.LIGNEDIRECTE),
            Line(83, "Directe 53", R.drawable.ligne_53, R.color.directe, ListGroup.LIGNEDIRECTE),
            Line(44, "Directe 55", R.drawable.ligne_55, R.color.directe, ListGroup.LIGNEDIRECTE),
            Line(85, "Directe 57", R.drawable.ligne_57, R.color.directe, ListGroup.LIGNEDIRECTE),
            Line(46, "TBNight", R.drawable.tbnight, R.color.tbnight, ListGroup.TBNIGHT),
            Line(88, "Locale 60", R.drawable.ligne_60, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(89, "Locale 61", R.drawable.ligne_61, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(49, "Locale 64", R.drawable.ligne_64, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(92, "Locale 65", R.drawable.ligne_65, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(50, "Locale 66", R.drawable.ligne_66, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(51, "Locale 67", R.drawable.ligne_67, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(95, "Locale 69", R.drawable.ligne_69, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(52, "Locale 70", R.drawable.ligne_70, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(96, "Locale 71", R.drawable.ligne_71, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(97, "Locale 72", R.drawable.ligne_72, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(53, "Locale 73", R.drawable.ligne_73, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(54, "Locale 74", R.drawable.ligne_74, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(98, "Locale 75", R.drawable.ligne_75, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(99, "Locale 76", R.drawable.ligne_76, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(100, "Locale 77", R.drawable.ligne_77, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(55, "Locale 78", R.drawable.ligne_78, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(101, "Locale 79", R.drawable.ligne_79, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(102, "Locale 80", R.drawable.ligne_80, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(103, "Locale 81", R.drawable.ligne_81, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(104, "Locale 82", R.drawable.ligne_82, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(105, "Locale 83", R.drawable.ligne_83, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(106, "Locale 84", R.drawable.ligne_84, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(107, "Locale 85", R.drawable.ligne_85, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(56, "Locale 86", R.drawable.ligne_86, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(57, "Locale 87", R.drawable.ligne_87, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(109, "Locale 89", R.drawable.ligne_89, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(110, "Locale 90", R.drawable.ligne_90, R.color.locale, ListGroup.LIGNELOCALE2),
            Line(79, "Flex'Artigues", R.drawable.flex_artigues, R.color.flex, ListGroup.LIGNELOCALE2),
            Line(118, "Navette Arena", R.drawable.navette_arena, R.color.navette_arena, ListGroup.LIGNESPECIALES),
            Line(117, "Navette Stade", R.drawable.navette_stade, R.color.navette_stade, ListGroup.LIGNESPECIALES),
            Line(123, "Navette Tram", R.drawable.navette_tram, R.color.navette_tram, ListGroup.LIGNESPECIALES),
            Line(119, "BatCUB", R.drawable.batcub, R.color.batcub, ListGroup.LIGNESPECIALES)
        )
    }
}