package model.DAO.AccessData

class NextSchedulesDestinationData {
    companion object {
        val destinations: Map<String, List<String>> = mapOf( 
            //5
            "5 Chemins" to listOf("LE HAILLAN", "5 Chemins"),
            //A
            "Aéroport" to listOf("MERIGNAC", "Aéroport"),
            "Arena" to listOf("FLOIRAC", "Arkéa Arena"),
            //B
            "Barbusse" to listOf("MERIGNAC", "Henri Barbusse"),
            "Barrière d'Ornano" to listOf("BORDEAUX", "Barrière d'Ornano"),
            "Base sous-marine" to listOf("BORDEAUX", "Base sous-marine"),
            "Bassins à Flot" to listOf("BORDEAUX", "Bassins à Flot"),
            "Beaudésert" to listOf("MERIGNAC", "Beaudésert"),
            "Beausite" to listOf("CENON", "Beausite"),
            "Beausoleil" to listOf("GRADIGNAN", "Beausoleil"),
            "Belle Rive" to listOf("SAINT LOUIS DE MONTFERRAND", "Belle Rive"),
            "Berges De La Garonne" to listOf("BORDEAUX", "Berges de la Garonne"),
            "Bougnard" to listOf("PESSAC", "Bougnard"),
            "Bouliac Centre Commercial" to listOf("BOULIAC", "Centre Commercial"),
            "Brandenburg" to listOf("BORDEAUX", "Brandenburg"),
            "Buttinière" to listOf("LORMONT", "Buttinière"),
            //C
            "Camille Jullian" to listOf("BORDEAUX", "Lycée Camille Jullian"),
            "Camping International" to listOf("BORDEAUX", "Camping International"),
            "Candau" to listOf("PESSAC", "Candau"),
            "Cantinolle" to listOf("EYSINES", "Cantinolle"),
            "Cap de Bos" to listOf("PESSAC", "Cap de Bos"),
            "Carle Vernet" to listOf("BORDEAUX", "Carle Vernet"),
            "Caychac" to listOf("BLANQUEFORT", "Caychac"),
            "Cenon Gare" to listOf("CENON", "Gare"),
            "Centre Commercial du Lac" to listOf("BORDEAUX", "Centre Commercial du Lac"),
            "Château Rouquey" to listOf("MERIGNAC", "Château Rouquey"),
            "Cimetière Intercommunal" to listOf("MERIGNAC", "Cimetière Intercommunal"),
            "Claveau" to listOf("BORDEAUX", "Claveau"),
            "Collège Claude Massé" to listOf("AMBARÈS", "Collège Claude Massé"),
            "Courréjean" to listOf("VILLENAVE D'ORNON", "Courréjean"),
            "Cracovie" to listOf("BORDEAUX", "Cracovie"),
            //D
            "Du Roy" to listOf("AMBARÈS", "Du Roy"),
            //E
            "Ecoparc" to listOf("BLANQUEFORT", "Ecoparc"),
            "Escarraguel" to listOf("AMBÈS", "Escarraguel"),
            //F
            "Floirac Dravemont" to listOf("FLOIRAC", "Dravemont"),
            "Fontaine d'Arlac" to listOf("MERIGNAC", "Fontaine d'Arlac"),
            "Fontaine D'Arlac" to listOf("MERIGNAC", "Fontaine d'Arlac"),
            "Fontanieu" to listOf("PAREMPUYRE", "Fontanieu"),
            "Fontderode" to listOf("ARTIGUES PRÈS BORDEAUX", "Fontderode"),
            "Fort Lajard" to listOf("AMBÈS", "Fort Lajard"),
            "France Alouette" to listOf("PESSAC", "France Alouette"),
            "Frankton" to listOf("BLANQUEFORT", "Frankton"),
            //G
            "Galin" to listOf("BORDEAUX", "Galin"),
            "Gambetta" to listOf("BORDEAUX", "Gambetta"),
            "Gare De Begles" to listOf("BÈGLES", "Gare"),
            "Gare De Blanquefort" to listOf("BLANQUEFORT", "Gare"),
            "Gare de Bruges" to listOf("BRUGES", "Gare"),
            "Gare Routière" to listOf("SAINT MÉDARD EN JALLES", "Gare Routière"),
            "Gare St Jean" to listOf("BORDEAUX", "Gare Saint Jean"),
            "G. Fauré" to listOf("BORDEAUX", "Gabriel Fauré"),
            "Gradignan Centre" to listOf("GRADIGNAN", "Centre"),
            "Grand Parc" to listOf("BORDEAUX", "Grand Parc"),
            //H
            "Hippodrome" to listOf("EYSINES", "Hippodrome"),
            "Hopital Pellegrin" to listOf("BORDEAUX", "Hôpital Pellegrin"),
            "Hôpital Pellegrin" to listOf("BORDEAUX", "Hôpital Pellegrin"),
            "Hôpital Suburbain" to listOf("LE BOUSCAT", "Hôpital Surburbain"),
            //I
            "Iris" to listOf("LORMONT", "Iris"),
            "Issac" to listOf("SAINT MÉDARD EN JALLES", "Issac"),
            //J
            "Jardin Botanique" to listOf("BORDEAUX", "Jardin Botanique"),
            //L
            "La Belle Etoile" to listOf("BOULIAC", "La Belle Étoile"),
            "La Boétie" to listOf("LE TAILLAN", "La Boétie"),
            "La Chênaie" to listOf("BASSENS", "La Chênaie"),
            "La Cite Du Vin" to listOf("BORDEAUX", "La Cité du Vin"),
            "La Gardette - Bassens - Carbon-Blanc" to listOf("BASSENS/CARBON BLANC", "La Gardette"),
            "La Gardette (Bassens - Carbon Blanc)" to listOf("BASSENS/CARBON BLANC", "La Gardette"),
            "La Mouline" to listOf("CARBON BLANC", "Mouline"),
            "Landegrand" to listOf("PAREMPUYRE", "Landegrand"),
            "La Renney" to listOf("BLANQUEFORT", "La Renney"),
            "Lauriers" to listOf("LORMONT", "Lauriers"),
            "Le Grand Caillou" to listOf("EYSINES", "Le Grand Caillou"),
            "Le Haillan Rostand" to listOf("LE HAILLAN", "Rostand"),
            "Le Plateau" to listOf("EYSINES", "Le Plateau"),
            "Les Ecoles" to listOf("MARTIGNAS SUR JALLE", "Les Écoles"),
            "Les Pins" to listOf("MERIGNAC", "Les Pins"),
            "Les Renardeaux" to listOf("MERIGNAC", "Les Renardeaux"),
            "Libération" to listOf("PAREMPUYRE", "Libération"),
            "Lormont Bas" to listOf("LORMONT", "Bas"),
            "Lycée Charles Peguy" to listOf("EYSINES", "Lycée Charles Peguy"),
            "Lycée Daguin" to listOf("MERIGNAC", "Lycée Daguin"),
            "Lycée des Graves" to listOf("GRADIGNAN", "Lycée des Graves"),
            "Lycée du Bâtiment (entrée)" to listOf("BLANQUEFORT", "Lycée du Bâtiment"),
            "Lycée Pape Clément" to listOf("PESSAC", "Lycée Pape Clément"),
            "Lycée Sud Médoc" to listOf("SAINT AUBIN", "Lycée Sud Médoc"),
            "Lycée Sud Médoc (Bois de Mont)" to listOf("LE TAILLAN", "Lycée Sud Médoc"),
            "Lycée Václav Havel" to listOf("BÈGLES", "Lycée Vàclav Havel"),
            //M
            "Magonty" to listOf("PESSAC", "Magonty"),
            "Malartic" to listOf("GRADIGNAN", "Malartic"),
            "Martignas Centre" to listOf("MARTIGNAS SUR JALLE", "Centre"),
            "Merignac Centre" to listOf("MERIGNAC", "Centre"),
            "Mérignac Centre" to listOf("MERIGNAC", "Centre"),
            "Mérignac Soleil" to listOf("MERIGNAC", "Soleil"),
            "Montaigne-Montesquieu" to listOf("PESSAC", "Montaigne Montesquieu"),
            //N
            "New York" to listOf("BORDEAUX", "New York"),
            //P
            "Palais de Justice" to listOf("BORDEAUX", "Palais de Justice"),
            "Parabelle" to listOf("AMBARÈS", "Parabelle"),
            "Parc des Expositions" to listOf("BORDEAUX", "Parc des Expositions"),
            "Parc Des Expositions - Nouveau Stade" to listOf("BORDEAUX", "Parc des Expositions"),
            "Peixotto" to listOf("TALENCE", "Peixotto"),
            "Pelouse de Douet" to listOf("BORDEAUX", "Pelouse de Douet"),
            "Pessac Centre" to listOf("PESSAC", "Centre"),
            "Phare" to listOf("MERIGNAC", "Phare"),
            "Photonique" to listOf("PESSAC", "Cité Photonique"),
            "Pin Galant" to listOf("MERIGNAC", "Pin Galant"),
            "Pinsoles" to listOf("SAINT AUBIN", "Pinsoles"),
            "Piscine Chambéry" to listOf("VILLENAVE D'ORNON", "Piscine Chambéry"),
            "Place Mondésir" to listOf("MERIGNAC", "Place Mondésir"),
            "Place Ravezies" to listOf("LE BOUSCAT", "Place Ravezies"),
            "Pont de la Maye" to listOf("VILLENAVE D'ORNON", "Pont de la Maye"),
            "Porte de Bourgogne" to listOf("BORDEAUX", "Porte de Bourgogne"),
            "Préfecture" to listOf("BORDEAUX", "Préfecture"),
            //R
            "René Coty" to listOf("AMBARÈS", "René Coty"),
            "République" to listOf("BORDEAUX", "République"),
            "Rives d'Arcins" to listOf("BÈGLES", "Rives d'Arcins"),
            "Romainville" to listOf("PESSAC", "Romainville"),
            "Rue Achard" to listOf("BORDEAUX", "Rue Achard"),
            //Q
            "Quai Français" to listOf("BASSENS", "Quai Français"),
            "Quinconces" to listOf("BORDEAUX", "Quinconces"),
            "Quinconces Fleuve" to listOf("BORDEAUX", "Quinconces Fleuve"),
            "Quinconces (Jean Jaurès)" to listOf("BORDEAUX", "Quinconces (Jean Jaurès)"),
            "Quinsus" to listOf("AMBARÈS", "Quinsus"),
            //S
            "Souge" to listOf("MARTIGNAS SUR JALLE", "Souge"),
            "Stade Matmut Atlantique" to listOf("BORDEAUX", "Stade Matmut Atlantique"),
            "Stade Ornon" to listOf("GRADIGNAN", "Stade Ornon"),
            "Stalingrad" to listOf("BORDEAUX", "Stalingrad"),
            "Stalingrad (Parlier)" to listOf("BORDEAUX", "Stalingrad"),
            "St Exupéry" to listOf("AMBÈS", "Saint Exupéry"),
            //T
            "Talence Centre-Forum" to listOf("TALENCE", "Forum"),
            "Tanaïs" to listOf("LE TAILLAN", "Tanaïs"),
            "Terres Neuves" to listOf("BÈGLES", "Terres Neuves"),
            "Thiers-Benauge" to listOf("BORDEAUX", "Thiers Benauge"),
            "Thouars" to listOf("TALENCE", "Thouars"),
            "Toctoucau" to listOf("PESSAC", "Toctoucau"),
            "Tout y Faut" to listOf("ARTIGUES PRÈS BORDEAUX", "Tout Y Faut"),
            //U
            "Unitec" to listOf("PESSAC", "Unitec"),
            //V
            "Delestage Terminus Vettiner" to listOf("BOULIAC", "Vettiner"),
            "Victoire (Pasteur)" to listOf("BORDEAUX", "Victoire"),
            "Village 5" to listOf("GRADIGNAN", "Village 5"),
            "Villenave Bourg" to listOf("VILLENAVE D'ORNON", "Bourg"),
            "Villenave Pyrénées" to listOf("VILLENAVE D'ORNON", "Pyrénées"),
            "Villepreux" to listOf("SAINT AUBIN", "Villepreux"),
            "Virecourt" to listOf("ARTIGUES PRÈS BORDEAUX", "Virecourt"),
            //Z
            "ZA Picot" to listOf("SAINT MÉDARD EN JALLES", "ZA Picot"),
            "Zone de Fret" to listOf("BRUGES", "Zone de Fret")
        )
    }
}