package model.DAO.AccessData

class PathDestinationData {
    companion object {
        val destinations: Map<String, List<String>> = mapOf(
            //5
            "5 Chemins" to listOf("LE HAILLAN", "5 Chemins", ""),
            "5 Chemins via THALES" to listOf("LE HAILLAN", "5 Chemins", "via Thalès"),
            //A
            "Aéroport" to listOf("MERIGNAC", "Aéroport", ""),
            "Alfred De Vigny" to listOf("MERIGNAC", "Alfred de Vigny", ""),
            "Arena" to listOf("FLOIRAC", "Arkéa Arena", ""),
            //B
            "Barbusse" to listOf("MERIGNAC", "Henri Barbusse", ""),
            "Barrière d'Ornano" to listOf("BORDEAUX", "Barrière d'Ornano", ""),
            "Barriere Du Medoc" to listOf("BORDEAUX", "Barrière du Médoc", ""),
            "Base sous-marine" to listOf("BORDEAUX", "Base sous-marine", ""),
            "Bassins à Flot" to listOf("BORDEAUX", "Bassins à Flot", ""),
            "Beaudésert" to listOf("MERIGNAC", "Beaudésert", ""),
            "Beausite" to listOf("CENON", "Beausite", ""),
            "Beausoleil" to listOf("GRADIGNAN", "Beausoleil", ""),
            "Belle Rive" to listOf("SAINT LOUIS DE MONTFERRAND", "Belle Rive", ""),
            "Belle Rive via CAT" to listOf("SAINT LOUIS DE MONTFERRAND", "Belle Rive", "via ESAT du GUA"),
            "Berges De La Garonne" to listOf("BORDEAUX", "Berges de la Garonne", ""),
            "Bougnard" to listOf("PESSAC", "Bougnard", ""),
            "Bougnard via ZAMAGE" to listOf("PESSAC", "Bougnard", "via ZA Magellan"),
            "Bouliac Centre Commercial" to listOf("BOULIAC", "Centre Commercial", ""),
            "Brandenburg" to listOf("BORDEAUX", "Brandenburg", ""),
            "Buttiniere" to listOf("LORMONT", "Buttinière", ""),
            "Buttinière" to listOf("LORMONT", "Buttinière", ""),
            "Buttinière via CCBLAN" to listOf("LORMONT", "Buttinière", "via Collège Simone Veil"),
            //C
            "Camille Jullian" to listOf("BORDEAUX", "Lycée Camille Jullian", ""),
            "Camping International" to listOf("BORDEAUX", "Camping International", ""),
            "Candau" to listOf("PESSAC", "Candau", ""),
            "Cantinolle" to listOf("EYSINES", "Cantinolle", ""),
            "Cantinolle via LSMED" to listOf("EYSINES", "Cantinolle", "via Lycée Sud Médoc"),
            "Capc Musee D'Art Contemporain" to listOf("BORDEAUX", "CAPC Musée d'Art Contemporain", ""),
            "Cap de Bos" to listOf("PESSAC", "Cap de Bos", ""),
            "Cap Metiers" to listOf("PESSAC", "Cap Métiers", ""),
            "Carbon-Blanc" to listOf("BASSENS/CARBON BLANC", "La Gardette", ""),
            "Carbon Blanc)" to listOf("BASSENS/CARBON BLANC", "La Gardette", ""),
            "Carbon Blanc) via COTE" to listOf("BASSENS/CARBON BLANC", "La Gardette", "via Avenue du Coteau"),
            "Carle Vernet" to listOf("BORDEAUX", "Carle Vernet", ""),
            "Caychac" to listOf("BLANQUEFORT", "Caychac", ""),
            "Caychac via LYPEGU" to listOf("BLANQUEFORT", "Caychac", "via Lycée Charles Peguy"),
            "Cenon Gare" to listOf("CENON", "Gare", ""),
            "Centre Commercial du Lac" to listOf("BORDEAUX", "Centre Commercial du Lac", ""),
            "Centre Commercial du Lac via PA" to listOf("BORDEAUX", "Centre Commercial du Lac", "via Pont d'Aquitaine"),
            "Chataigneraie" to listOf("PESSAC", "Châtaigneraie", ""),
            "Château Rouquey" to listOf("MERIGNAC", "Château Rouquey", ""),
            "Cimetière Intercommunal" to listOf("MERIGNAC", "Cimetière Intercommunal", ""),
            "Cimetière Intercommunal via BA106" to listOf("MERIGNAC", "Cimetière Intercommunal", "via BA 106"),
            "Claveau" to listOf("BORDEAUX", "Claveau", ""),
            "Collège Claude Massé" to listOf("AMBARÈS", "Collège Claude Massé", ""),
            "Collège Simone Veil" to listOf("CARBON BLANC", "Collège Simone Veil", ""),
            "Courréjean" to listOf("VILLENAVE D'ORNON", "Courréjean", ""),
            "Courréjean via IMA" to listOf("VILLENAVE D'ORNON", "Courréjean", "via IMA"),
            "Courréjean via THALES" to listOf("VILLENAVE D'ORNON", "Courréjean", "via Thalès"),
            "Cracovie" to listOf("BORDEAUX", "Cracovie", ""),
            //D
            "Delestage Terminus Vettiner" to listOf("BOULIAC", "Vettiner", ""),
            "Doyen Brus" to listOf("PESSAC", "Doyen Brus", ""),
            "Du Roy" to listOf("AMBARÈS", "Du Roy", ""),
            //E
            "Ecoparc" to listOf("BLANQUEFORT", "Ecoparc", ""),
            "Ecoparc via LYPEGU" to listOf("BLANQUEFORT", "Ecoparc", "via Lycée Charles Peguy"),
            "Escarraguel" to listOf("AMBÈS", "Escarraguel", ""),
            "Eysines Centre" to listOf("EYSINES", "Centre", ""),
            //F
            "Floirac Dravemont" to listOf("FLOIRAC", "Dravemont", ""),
            "Fontaine D'Arlac" to listOf("MERIGNAC", "Fontaine d'Arlac", ""),
            "Fontaine d'Arlac" to listOf("MERIGNAC", "Fontaine d'Arlac", ""),
            "Fontaine d'Arlac via TROMAI" to listOf("MERIGNAC", "Fontaine d'Arlac", ""),
            "Fontanieu" to listOf("PAREMPUYRE", "Fontanieu", ""),
            "Fontderode" to listOf("ARTIGUES PRÈS BORDEAUX", "Fontderode", ""),
            "Fort Lajard" to listOf("AMBÈS", "Fort Lajard", ""),
            "Fort Lajard via CCBLAN" to listOf("AMBÈS", "Fort Lajard", "via Collège Simone Veil"),
            "France Alouette" to listOf("PESSAC", "France Alouette", ""),
            "Frankton" to listOf("BLANQUEFORT", "Frankton", ""),
            //G
            "Galin" to listOf("BORDEAUX", "Galin", ""),
            "Gare De Begles" to listOf("BÈGLES", "Gare", ""),
            "Gare De Blanquefort" to listOf("BLANQUEFORT", "Gare", ""),
            "Gare de Bruges" to listOf("BRUGES", "Gare", ""),
            "Gare De Pessac Alouette" to listOf("PESSAC", "Gare Pessac Alouette", ""),
            "Gare Routière" to listOf("SAINT MÉDARD EN JALLES", "Gare Routière", ""),
            "Gare Saint-Jean" to listOf("BORDEAUX", "Gare Saint Jean", ""),
            "Gare St Jean" to listOf("BORDEAUX", "Gare Saint Jean", ""),
            "Gavinies" to listOf("BORDEAUX", "Gaviniès", ""),
            "Gaviniès" to listOf("BORDEAUX", "Gaviniès", ""),
            "G. Fauré" to listOf("BORDEAUX", "Gabriel Fauré", ""),
            "Gradignan Centre" to listOf("GRADIGNAN", "Centre", ""),
            "Grand Parc" to listOf("BORDEAUX", "Grand Parc", ""),
            //H
            "Hippodrome" to listOf("LE BOUSCAT", "Hippodrome", ""),
            "Hopital Haut Leveque" to listOf("PESSAC", "Hôpital Haut Levêque", ""),
            "Hopital Pellegrin" to listOf("BORDEAUX", "Hôpital Pellegrin", ""),
            "Hôpital Pellegrin" to listOf("BORDEAUX", "Hôpital Pellegrin", ""),
            "Hôpital Suburbain" to listOf("LE BOUSCAT", "Hôpital Suburbain", ""),
            //I
            "Iris" to listOf("LORMONT", "Iris", ""),
            "Issac" to listOf("SAINT MÉDARD EN JALLES", "Issac", ""),
            //J
            "Jardin Botanique" to listOf("BORDEAUX", "Jardin Botanique", ""),
            "Julien" to listOf("SAINT MÉDARD EN JALLES", "Julien", ""),
            //L
            "La Belle Etoile" to listOf("BOULIAC", "La Belle Étoile", ""),
            "La Belle Etoile via COTE" to listOf("BOULIAC", "La Belle Étoile", "via Avenue du Coteau"),
            "La Belle Etoile via COTEA" to listOf("BOULIAC", "La Belle Étoile", "via Avenue du Coteau"),
            "La Boétie" to listOf("LE TAILLAN", "La Boétie", ""),
            "La Boétie via HOTA" to listOf("LE TAILLAN", "La Boétie", "via Hontane"),
            "La Chênaie" to listOf("BASSENS", "La Chênaie", ""),
            "La Chênaie via CAT" to listOf("BASSENS", "La Chênaie", "via ESAT du GUA"),
            "La Cite Du Vin" to listOf("BORDEAUX", "La Cité du Vin", ""),
            "La Cité du Vin" to listOf("BORDEAUX", "La Cité du Vin", ""),
            "La Morlette" to listOf("CENON", "La Morlette", ""),
            "La Mouline" to listOf("CARBON BLANC", "Mouline", ""),
            "Landegrand" to listOf("PAREMPUYRE", "Landegrand", ""),
            "La Renney" to listOf("BLANQUEFORT", "La Renney", ""),
            "Lauriers" to listOf("LORMONT", "Lauriers", ""),
            "La Vache" to listOf("BRUGES", "La Vache", ""),
            "Le Grand Caillou" to listOf("EYSINES", "Le Grand Caillou", ""),
            "Le Haillan Rostand" to listOf("LE HAILLAN", "Rostand", ""),
            "Le Haillan Rostand via LSMED" to listOf("LE HAILLAN", "Rostand", "via Lycée Sud Médoc"),
            "Le Plateau" to listOf("EYSINES", "Le Plateau", ""),
            "Les Aubiers" to listOf("BORDEAUX", "Les Aubiers", ""),
            "Les Ecoles" to listOf("MARTIGNAS SUR JALLE", "Les Écoles", ""),
            "Les Hangars (Médoc)" to listOf("BORDEAUX", "Les Hangars", ""),
            "Les Pins" to listOf("MARTIGNAS SUR JALLE", "Les Pins", ""),
            "Les Pins via IMA" to listOf("MARTIGNAS SUR JALLE", "Les Pins", "via IMA"),
            "Les Renardeaux" to listOf("MERIGNAC", "Les Renardeaux", ""),
            "Les Renardeaux via BA106" to listOf("MERIGNAC", "Les Renardeaux", "via BA 106"),
            "Les Sources" to listOf("EYSINES", "Les Sources", ""),
            "Libération" to listOf("PAREMPUYRE", "Libération", ""),
            "Lormont Bas" to listOf("LORMONT", "Bas", ""),
            "Lormont Bas via CITE DU VIN" to listOf("LORMONT", "Bas", "via La Cité du Vin"),
            "Lormont Bas via HANGARS" to listOf("LORMONT", "Bas", "via Les Hangars"),
            "Lormont Bas via HANGARS ET CDV" to listOf("LORMONT", "Bas", "via Les Hangars et La Cité du Vin"),
            "Lycée du Bâtiment (entrée)" to listOf("BLANQUEFORT", "Lycée du Bâtiment", ""),
            "Lycée Charles Peguy" to listOf("EYSINES", "Lycée Charles Peguy", ""),
            "Lycée Daguin" to listOf("MERIGNAC", "Lycée Daguin", ""),
            "Lycée des Graves" to listOf("GRADIGNAN", "Lycée des Graves", ""),
            "Lycée Pape Clément" to listOf("PESSAC", "Lycée Pape Clément", ""),
            "Lycée Sud Médoc" to listOf("SAINT AUBIN", "Lycée Sud Médoc", ""),
            "Lycée Sud Médoc (Bois de Mont)" to listOf("LE TAILLAN", "Lycée Sud Médoc", ""),
            "Lycée Sud Médoc via BA106" to listOf("SAINT AUBIN", "Lycée Sud Médoc", "via BA 106"),
            "Lycee Vaclav Havel" to listOf("BÈGLES", "Lycée Vàclav Havel", ""),
            "Lycée Václav Havel" to listOf("BÈGLES", "Lycée Vàclav Havel", ""),
            //M
            "Magonty" to listOf("PESSAC", "Magonty", ""),
            "Mairie Du Bouscat" to listOf("LE BOUSCAT", "Mairie", ""),
            "Malartic" to listOf("GRADIGNAN", "Malartic", ""),
            "Martignas Centre" to listOf("MARTIGNAS SUR JALLE", "Centre", ""),
            "Meriadeck" to listOf("BORDEAUX", "Mériadeck", ""),
            "Mériadeck" to listOf("BORDEAUX", "Mériadeck", ""),
            "Merignac Aeroport" to listOf("MERIGNAC", "Aéroport", ""),
            "Merignac Centre" to listOf("MERIGNAC", "Centre", ""),
            "Mérignac Centre" to listOf("MERIGNAC", "Centre", ""),
            "Mérignac Soleil" to listOf("MERIGNAC", "Soleil", ""),
            "Montaigne-Montesquieu" to listOf("PESSAC", "Montaigne Montesquieu", ""),
            "Musee D'Aquitaine" to listOf("BORDEAUX", "Musée d'Aquitaine", ""),
            "Museum" to listOf("BORDEAUX", "Fondaudège Muséum", ""),
            //N
            "New York" to listOf("BORDEAUX", "New York", ""),
            "Nouveau Stade" to listOf("BORDEAUX", "Parc des Expositions", ""),
            //P
            "Palais de Justice" to listOf("BORDEAUX", "Palais de Justice", ""),
            "Palais de Justice via ZAMAGE" to listOf("BORDEAUX", "Palais de Justice", "via ZA Magellan"),
            "Parabelle" to listOf("AMBARÈS", "Parabelle", ""),
            "Parabelle via PA" to listOf("AMBARÈS", "Parabelle", "via Pont d'Aquitaine"),
            "Parc des Expositions" to listOf("BORDEAUX", "Parc des Expositions", ""),
            "Peixotto" to listOf("TALENCE", "Peixotto", ""),
            "Pelouse de Douet" to listOf("BORDEAUX", "Pelouse de Douet", ""),
            "Pessac Centre" to listOf("PESSAC", "Centre", ""),
            "Phare" to listOf("MERIGNAC", "Phare", ""),
            "Phare via LYPEGU" to listOf("MERIGNAC", "Phare", "via Lycée Charles Peguy"),
            "Photonique" to listOf("PESSAC", "Cité Photonique", ""),
            "Picot" to listOf("EYSINES", "Picot", ""),
            "Pin Galant" to listOf("MERIGNAC", "Pin Galant", ""),
            "Pinsoles" to listOf("SAINT AUBIN", "Pinsoles", ""),
            "Pinsoles via LSMED" to listOf("SAINT AUBIN", "Pinsoles", "via Lycée Sud Médoc"),
            "Piscine Chambéry" to listOf("VILLENAVE D'ORNON", "Piscine Chambéry", ""),
            "Place De La Bourse" to listOf("BORDEAUX", "Place de la Bourse", ""),
            "Place Mondésir" to listOf("MERIGNAC", "Place Mondésir", ""),
            "Place Ravezies" to listOf("LE BOUSCAT", "Place Ravezies", ""),
            "Place Ravezies via COTEA" to listOf("LE BOUSCAT", "Place Ravezies", "via Avenue du Coteau"),
            "Pont de la Maye" to listOf("VILLENAVE D'ORNON", "Pont de la Maye", ""),
            "Porte de Bourgogne" to listOf("BORDEAUX", "Porte de Bourgogne", ""),
            "Porte De Bourgogne" to listOf("BORDEAUX", "Porte de Bourgogne", ""),
            "Préfecture" to listOf("BORDEAUX", "Préfecture", ""),
            //Q
            "Quai Français" to listOf("BASSENS", "Quai Français", ""),
            "Quarante Journaux" to listOf("BORDEAUX", "Quarante Journaux", ""),
            "Quatre Chemins" to listOf("MERIGNAC", "4 Chemins", ""),
            "Quinconces" to listOf("BORDEAUX", "Quinconces", ""),
            "Quinconces Fleuve" to listOf("BORDEAUX", "Quinconces Fleuve", ""),
            "Quinconces (Jean Jaurès)" to listOf("BORDEAUX", "Quinconces (Jean Jaurès)", ""),
            "Quinconces (Jean Jaurès) via CITE DU VIN" to listOf("BORDEAUX", "Quinconces (Jean Jaurès)", "via La Cité du Vin"),
            "Quinconces (Jean Jaurès) via HANGARS" to listOf("BORDEAUX", "Quinconces (Jean Jaurès)", "via Les Hangars"),
            "Quinconces via HOTA" to listOf("BORDEAUX", "Quinconces", "via Hontane"),
            "Quinconces via LSMED" to listOf("BORDEAUX", "Quinconces", "via Lycée Sud Médoc"),
            "Quinsus" to listOf("AMBARÈS", "Quinsus", ""),
            "Quinsus via PA" to listOf("AMBARÈS", "Quinsus", "via Pont d'Aquitaine"),
            //R
            "René Coty" to listOf("AMBARÈS", "René Coty", ""),
            "République" to listOf("BORDEAUX", "République", ""),
            "République via ZAMAGE" to listOf("BORDEAUX", "République", "via ZA Magellan"),
            "Rives d'Arcins" to listOf("BÈGLES", "Rives d'Arcins", ""),
            "Roger Allo" to listOf("BORDEAUX", "Roger Allo", ""),
            "Romainville" to listOf("PESSAC", "Romainville", ""),
            "RPA Villa Nova" to listOf("VILLENAVE D'ORNON", "RPA Villa Nova", ""),
            "Rue Achard" to listOf("BORDEAUX", "Rue Achard", ""),
            //S
            "Saint-Augustin" to listOf("BORDEAUX", "Saint Augustin", ""),
            "Sainte-Catherine" to listOf("BORDEAUX", "Sainte Catherine", ""),
            "Saint-Michel" to listOf("BORDEAUX", "Saint Michel", ""),
            "Saint-Nicolas" to listOf("BORDEAUX", "Saint Nicolas", ""),
            "Souge" to listOf("MARTIGNAS SUR JALLE", "Souge", ""),
            "Stade Matmut Atlantique" to listOf("BORDEAUX", "Stade Matmut Atlantique", ""),
            "Stade Ornon" to listOf("GRADIGNAN", "Stade Ornon", ""),
            "Stalingrad" to listOf("BORDEAUX", "Stalingrad", ""),
            "Stalingrad (Parlier)" to listOf("BORDEAUX", "Stalingrad", ""),
            "Stalingrad (Parlier) via CDV ET HANGARS" to listOf("BORDEAUX", "Stalingrad", "via La Cité du Vin et Les Hangars"),
            "Stalingrad (Parlier) via CITE DU VIN" to listOf("BORDEAUX", "Stalingrad", "via La Cité du Vin"),
            "Stalingrad (Tram A)" to listOf("BORDEAUX", "Stalingrad", "via Collège Simone Veil"),
            "Stalingrad via CCBLAN" to listOf("BORDEAUX", "Stalingrad", "via Collège Simone Veil"),
            "St Exupéry" to listOf("AMBÈS", "Saint Exupéry", ""),
            "St Exupéry via CCBLAN" to listOf("AMBÈS", "Saint Exupéry", "via Collège Simone Veil"),
            //T
            "Taillan Cimetière" to listOf("LE TAILLAN", "Cimetière", ""),
            "Talence Centre-Forum" to listOf("TALENCE", "Forum", ""),
            "Tanaïs" to listOf("LE TAILLAN", "Tanaïs", ""),
            "Terres Neuves" to listOf("BÈGLES", "Terres Neuves", ""),
            "Term Aeroport" to listOf("MERIGNAC", "Aéroport", ""),
            "Thiers-Benauge" to listOf("BORDEAUX", "Thiers Benauge", ""),
            "Thouars" to listOf("TALENCE", "Thouars", ""),
            "Toctoucau" to listOf("PESSAC", "Toctoucau", ""),
            "Toctoucau via TROMAI" to listOf("PESSAC", "Toctoucau", ""),
            "Tout y Faut" to listOf("ARTIGUES PRÈS BORDEAUX", "Tout Y Faut", ""),
            "Treulon" to listOf("LE BOUSCAT", "Champs de Courses - Treulon", ""),
            //U
            "Unitec" to listOf("PESSAC", "Unitec", ""),
            //V
            "Vettiner" to listOf("BOULIAC", "Vettiner", ""),
            "Victoire (Pasteur)" to listOf("BORDEAUX", "Victoire", ""),
            "Village 5" to listOf("GRADIGNAN", "Village 5", ""),
            "Villenave Bourg" to listOf("VILLENAVE D'ORNON", "Bourg", ""),
            "Villenave Pyrénées" to listOf("VILLENAVE D'ORNON", "Pyrénées", ""),
            "Villepreux" to listOf("SAINT AUBIN", "Villepreux", ""),
            "Villepreux via LSMED" to listOf("SAINT AUBIN", "Villepreux", "via Lycée Sud Médoc"),
            "Virecourt" to listOf("ARTIGUES PRÈS BORDEAUX", "Virecourt", ""),
            //Z
            "ZA Picot" to listOf("SAINT MÉDARD EN JALLES", "ZA Picot", ""),
            "ZA Picot via LSMED" to listOf("SAINT MÉDARD EN JALLES", "ZA Picot", "via Lycée Sud Médoc"),
            "Zone de Fret" to listOf("BRUGES", "Zone de Fret", ""),
        )
    }
}